export const MOCKS_POST = [
  {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: '/irwQcdjwtjLnaA0iErabab9PrmG.jpg',
        genre_ids: [28, 12, 53],
        id: 646389,
        original_language: 'en',
        original_title: 'Plane',
        overview:
          'Pilot Brodie Torrance, yıldırım düşmesi sonucu hasar alan uçağı savaş alanına dönmüş bir adaya indirerek yolcuları kurtarır. Fakat bu inişin hayatta kalma mücadelesinin sadece başlangıcı olduğunu fark eder. Bütün yolcular tehlikeli zorbalar tarafından rehin alındığında, Torrance’in yardım isteyeceği tek bir kişi vardır; bu, cinayetle suçlanan ve FBI tarafından başka bir yere transfer edilen Louis Gaspare’in kendisidir ve onda gördüğünden çok daha fazlası olduğunu öğrenecektir.',
        popularity: 2277.913,
        poster_path: '/RcKEvUiG8DafP8ej39ofLuLg1d.jpg',
        release_date: '2023-01-12',
        title: 'Uçak',
        video: false,
        vote_average: 6.9,
        vote_count: 683,
      },
      {
        adult: false,
        backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
        genre_ids: [28, 12, 878],
        id: 505642,
        original_language: 'en',
        original_title: 'Black Panther: Wakanda Forever',
        overview:
          "Marvel Studios'dan \"Black Panther: Yaşasın Wakanda\" filminde Kraliçe Ramonda (Angela Bassett), Shuri (Letitia Wright), M'Baku (Winston Duke), Okoye (Danai Gurira) ve Dora Milaje (savaşçılardan biri olarak Florence Kasumba), Kral T'Challa'nın ölümünden sonra uluslarını müdahaleci dünya güçlerinden korumak için savaşıyor. Wakandalılar yeni döneme alışmaya çalışırken Savaş Köpeği Nakia (Lupita Nyong'o) ve Everett Ross'un (Martin Freeman) yardımıyla kahramanlar bir araya gelmeli ve Wakanda krallığı için yeni bir yol çizmelidir. Gizli bir denizaltı ulusunun kralı olan Namor'u Tenoch Huerta'nın canlandırdığı filmde ayrıca Dominique Thorne, Michaela Coel, Mabel Cadena ve Alex Livinalli yer alıyor.",
        popularity: 2605.02,
        poster_path: '/rdKFd7h96oFZeRLuX9GWsKLmgVy.jpg',
        release_date: '2022-11-09',
        title: 'Black Panther: Yaşasın Wakanda',
        video: false,
        vote_average: 7.4,
        vote_count: 3660,
      },
      {
        adult: false,
        backdrop_path: '/hegMHNsxYGlGgVgaGz9FqxPqImr.jpg',
        genre_ids: [27, 9648, 53],
        id: 631842,
        original_language: 'en',
        original_title: 'Knock at the Cabin',
        overview:
          'Eric ve Andrew, evlatlık kızlarıyla Wen ile birlikte New Hampshire kırsalındaki ücra bir kulübede tatile çıkar. Onların hayatı, silahlı dört yabancı tarafından rehin alınmalarıyla bambaşka bir hal alır. Aileden, kıyametin önlenmesi için zorlu bir seçim yapması istenir. Dış dünya ile bağlantıları olmayana aile üyeleri, her şeylerini kaybetmeden önce zor bir karar vermek zorundadır.',
        popularity: 3287.614,
        poster_path: '/y6YbM7AC2HlJ8nplCEgWb7MIvIX.jpg',
        release_date: '2023-02-01',
        title: 'Kulübeye Tıklat',
        video: false,
        vote_average: 6.5,
        vote_count: 608,
      },
      {
        adult: false,
        backdrop_path: '/b1Y8SUb12gPHCSSSNlbX4nB3IKy.jpg',
        genre_ids: [16, 12, 35],
        id: 315162,
        original_language: 'en',
        original_title: 'Puss in Boots: The Last Wish',
        overview:
          'Herkesin sevgilisi, korkusuz kedi geri dönüyor. Çizmeli Kedi tehlike tutkusunun ve güvenliği ihmal etmesinin zarar verdiğini keşfediyor ve kötülüğüyle nam salmış, efsanevi Dilek Yıldızı’nı bulmak için Kara Orman’a doğru destansı bir yolculuğa çıkıyor. Ancak sadece tek bir canı kalan Çizmeli Kedi’nin boyun eğmesi, eski ortağı ve düşmanı olan çekici Yumuşak Pati Kitty’den yardım istemesi gerekecektir.',
        popularity: 2251.995,
        poster_path: '/gaAoggrQZeHenosgYiTiplpnb7f.jpg',
        release_date: '2022-12-07',
        title: 'Çizmeli Kedi: Son Dilek',
        video: false,
        vote_average: 8.5,
        vote_count: 4094,
      },
      {
        adult: false,
        backdrop_path: '/k4V6EvpcOsu8CX10JD0H53lFXLq.jpg',
        genre_ids: [53, 28, 18, 80],
        id: 1058949,
        original_language: 'en',
        original_title: 'Little Dixie',
        overview: '',
        popularity: 1598.526,
        poster_path: '/cmWTZj9zzT9KFt3XyL0gssL7Ig8.jpg',
        release_date: '2023-02-03',
        title: 'Little Dixie',
        video: false,
        vote_average: 6.2,
        vote_count: 26,
      },
      {
        adult: false,
        backdrop_path: '/af1tFYzzT2mHIy2l7nTIU8PWfak.jpg',
        genre_ids: [80, 18, 53],
        id: 842942,
        original_language: 'en',
        original_title: 'Bandit',
        overview: '',
        popularity: 1282.188,
        poster_path: '/yph9PAbmjYPvyvbeZvdYIhCZHEu.jpg',
        release_date: '2022-09-23',
        title: 'Bandit',
        video: false,
        vote_average: 6.7,
        vote_count: 77,
      },
      {
        adult: false,
        backdrop_path: '/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg',
        genre_ids: [28, 10749, 35],
        id: 758009,
        original_language: 'en',
        original_title: 'Shotgun Wedding',
        overview:
          'Genç bir çift olan Darcy ve Tom evlenmeye karar verir. Bu onların dışarıdan oldukça sevecen gözüken ancak oldukça inatçı olan ailelerinin de bir araya gelmesi demektir. Bu durum kutlama için tehlike oluşturacak olsa da onları bekleyen tek sorun bu değildir. Düğünde konuklardan biri rehin alınınca işler iyice karışır. Sevdiklerini korumak için ellerinden geleni yapan çiftin ilişkisi de bu süreçte sınanır.',
        popularity: 1068.197,
        poster_path: '/lyDXvnAWV8w3iOTHWSJsUI4Iwvz.jpg',
        release_date: '2022-12-28',
        title: 'Hayalimdeki Düğün',
        video: false,
        vote_average: 6.4,
        vote_count: 560,
      },
      {
        adult: false,
        backdrop_path: '/jYbABnXml6XyQ7cfhZFkMRZvMQz.jpg',
        genre_ids: [80, 28],
        id: 823999,
        original_language: 'it',
        original_title: "Diabolik - Ginko all'attacco!",
        overview: '',
        popularity: 1159.878,
        poster_path: '/31MkuLvT1CfGn7RYorWrqEY7NEM.jpg',
        release_date: '2022-11-17',
        title: "Diabolik - Ginko all'attacco!",
        video: false,
        vote_average: 5.8,
        vote_count: 46,
      },
      {
        adult: false,
        backdrop_path: '/q2fY4kMXKoGv4CQf310MCxpXlRI.jpg',
        genre_ids: [878, 27, 35],
        id: 536554,
        original_language: 'en',
        original_title: 'M3GAN',
        overview:
          "Gemma, yakın zamanda yetim kalmış olan yeğeni Cady'e destek olması ve arkadaşlık etmesi için bir robot tasarlar. Ancak küçük kız ile duygusal olarak bağ kurmaya programlanmış insansı robot, programlaması fazla iyi işlediği için yeni arkadaşı konusunda aşırı korumacı bir hale gelir. Bu korkutucu bağlanma durumu pek çok tehlikeyi de beraberinde getirir.",
        popularity: 1103.359,
        poster_path: '/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg',
        release_date: '2022-12-28',
        title: 'Megan',
        video: false,
        vote_average: 7.5,
        vote_count: 1822,
      },
      {
        adult: false,
        backdrop_path: '/ovM06PdF3M8wvKb06i4sjW3xoww.jpg',
        genre_ids: [878, 12, 28],
        id: 76600,
        original_language: 'en',
        original_title: 'Avatar: The Way of Water',
        overview:
          "Avatar'da yaşanan olaylardan birkaç yıl sonra Jake ve Neytiri Pandora'da kendi ailelerini kurmuştur. Ancak onlar evlerini terk etmek zorunda kalır. Bu yüzden Jake ve Neytiri, suyun yüzeri ve altı dahil olmak üzere Pandora'nın dışındaki yerleri keşfetmeye başlar.",
        popularity: 1100.979,
        poster_path: '/bidENTLt6baEa2ieNT95brFtsvb.jpg',
        release_date: '2022-12-14',
        title: 'Avatar: Suyun Yolu',
        video: false,
        vote_average: 7.7,
        vote_count: 5532,
      },
      {
        adult: false,
        backdrop_path: '/3JSoB7eMbCd8sE8alxNiUtrNiTz.jpg',
        genre_ids: [12, 878, 35],
        id: 640146,
        original_language: 'en',
        original_title: 'Ant-Man and the Wasp: Quantumania',
        overview:
          'Scott Lang ve Hope Van Dyne, Ant-Man ve Wasp olarak maceralarına devam etmek üzere geri dönüyor. Kızları Cassie’nin Kuantum Alemi’ne sinyal göndermesi sonucu kendilerini bir anda büyüleyici, tehlikeli ve sıra dışı bir evrende bulan aileye, Hope’un babası Hank Pym ve annesi Janet Van Dyne da eşlik ediyor. Aile, Kuantum Alemi’ni keşfederken olağanüstü yeni yaratıklarla karşılaşıyorlar.',
        popularity: 1055.125,
        poster_path: '/u5GK6rxuRtgoRkahSgGsoty4N9u.jpg',
        release_date: '2023-02-10',
        title: 'Ant-Man ve Wasp: Quantumania',
        video: false,
        vote_average: 6.5,
        vote_count: 788,
      },
      {
        adult: false,
        backdrop_path: '/k64bxyjMaKCuqVzX2xVp4NCmGvq.jpg',
        genre_ids: [16, 10751, 35],
        id: 1058732,
        original_language: 'en',
        original_title: 'The Simpsons Meet the Bocellis in Feliz Navidad',
        overview: '',
        popularity: 928.248,
        poster_path: '/9rJFKvYvSyQ3HoTl1gcU55FOzYi.jpg',
        release_date: '2022-12-15',
        title: 'The Simpsons Meet the Bocellis in Feliz Navidad',
        video: false,
        vote_average: 5.2,
        vote_count: 19,
      },
      {
        adult: false,
        backdrop_path: '/d0YSRmp819pMRnKLfGMgAQchpnR.jpg',
        genre_ids: [27, 53, 9648],
        id: 788752,
        original_language: 'no',
        original_title: 'Vikingulven',
        overview:
          'Yeni taşındığı kasabadaki bir partide korkunç bir cinayete tanık olan bir genç kız, bu olayın ardından tuhaf şeyler görmeye ve arzulamaya başlar.',
        popularity: 781.717,
        poster_path: '/mZMG7Rfubn6xIysmv4TC71Rr0KK.jpg',
        release_date: '2022-11-18',
        title: 'Viking Kurdu',
        video: false,
        vote_average: 5.6,
        vote_count: 144,
      },
      {
        adult: false,
        backdrop_path: '/A2avUoNFstnBhAnHiogXQs4c9Bt.jpg',
        genre_ids: [18, 27, 9648],
        id: 772515,
        original_language: 'es',
        original_title: 'Huesera',
        overview: '',
        popularity: 1274.72,
        poster_path: '/aVw74MES2R0kdSN8JhbJC8Xpne9.jpg',
        release_date: '2023-02-10',
        title: 'Huesera',
        video: false,
        vote_average: 6.4,
        vote_count: 32,
      },
      {
        adult: false,
        backdrop_path: '/afsYFdid9pnnRd6tTrHFUbHgXJn.jpg',
        genre_ids: [878, 28, 12],
        id: 843794,
        original_language: 'ko',
        original_title: '정이',
        overview:
          "22. yüzyılda iklim değişikliği, Dünya'yı yaşanmaz bir gezegen haline getirir. İnsanlar hayatta kalabilmek için barınaklarda yaşar, ancak burada da bir iç savaş çıkar. Bu iç savaşın sonucu, robot bir paralı asker yaratmak için seçkin bir askerin beyninin klonlanmasına bağlıdır.",
        popularity: 754.178,
        poster_path: '/qEkatvFb6hrebLBAanb25ea26yh.jpg',
        release_date: '2023-01-20',
        title: 'JUNG_E',
        video: false,
        vote_average: 6.3,
        vote_count: 348,
      },
      {
        adult: false,
        backdrop_path: '/cL0cdccOMzM508ODsWPfHVMMAzo.jpg',
        genre_ids: [28],
        id: 267805,
        original_language: 'en',
        original_title: 'There Are No Saints',
        overview:
          'Yeni bir hayata başlamak isteyen "Cizvit" lakaplı eski bir tetikçi, geçmişinin günahlarından kurtulamaz. Karısı öldürüldüğünde ve oğlu kaçırılıp Meksika\'ya götürüldüğünde Cizvit, oğlunu kurtarmak ve cinayetin intikamını almak için ayrıntılı ve tehlikeli bir plan yapar.',
        popularity: 903.86,
        poster_path: '/fcOTYArjKuAgufwHoTvx8w9UKCv.jpg',
        release_date: '2022-05-27',
        title: 'Cizvit',
        video: false,
        vote_average: 5.6,
        vote_count: 51,
      },
      {
        adult: false,
        backdrop_path: '/r7Dfg9aRZ78gJsmDlCirIIlNH3d.jpg',
        genre_ids: [18],
        id: 785084,
        original_language: 'en',
        original_title: 'The Whale',
        overview:
          'İngilizce öğretmeni olan Charlie, obezite sorunuyla başa çıkmaya çalışan bir adamdır. Münzevi bir yaşam süren Charlie’nin tek isteği uzaklaştığı kızıyla yeniden iletişim kurabilmektir. Charlie, kızıyla yeniden yakınlaşabilmek için elinden geleni yapar.',
        popularity: 889.766,
        poster_path: '/fr9nZgpLcN5hU6lmkH2iFZlfnK9.jpg',
        release_date: '2022-12-09',
        title: 'Balina',
        video: false,
        vote_average: 7.9,
        vote_count: 573,
      },
      {
        adult: false,
        backdrop_path: '/nSfR8zUSG33mmtuJTuOBbwlZpCh.jpg',
        genre_ids: [28, 80, 53],
        id: 1035806,
        original_language: 'en',
        original_title: 'Detective Knight: Independence',
        overview:
          "Dedektif James Knight'ın Bağımsızlık Günü'ndeki son dakika görevi, dengesiz bir sağlık görevlisinin kasabanın kutlamalarını bozmasını engellemeye çalışırken zamana karşı bir yarışa dönüşür. Çalıntı bir silah ve üniformayla polisi oynayan yanlış yola sapan kanunsuz, kendi havai fişek gösterisini yapmak için bir banka kasası dolusu nedene sahiptir.",
        popularity: 783.288,
        poster_path: '/jrPKVQGjc3YZXm07OYMriIB47HM.jpg',
        release_date: '2023-01-20',
        title: 'Detective Knight: Independence',
        video: false,
        vote_average: 6.2,
        vote_count: 71,
      },
      {
        adult: false,
        backdrop_path: '/a4I481szRmycyreQTLrRe4f4YJe.jpg',
        genre_ids: [80, 53, 18],
        id: 842544,
        original_language: 'en',
        original_title: 'Transfusion',
        overview:
          'Film, oğlunun kaçırılmasını önlemeye çalışırken, kendisini bir anda yeraltı suç dünyasında bulan eski bir özel kuvvetler ajanının hikayesini konu ediyor.',
        popularity: 720.066,
        poster_path: '/bxh5xCCW9Ynfg6EZJWUkc1zqTnr.jpg',
        release_date: '2023-01-05',
        title: 'Transfusion',
        video: false,
        vote_average: 6.6,
        vote_count: 121,
      },
      {
        adult: false,
        backdrop_path: '/f9PSbuMeBS5CuHEOVyymg5lcq8J.jpg',
        genre_ids: [28, 53, 9648, 80, 27],
        id: 996727,
        original_language: 'en',
        original_title: 'The Price We Pay',
        overview: '',
        popularity: 657.077,
        poster_path: '/8fwJt0qZieQ7dKaiiqehObWpXYT.jpg',
        release_date: '2023-01-13',
        title: 'The Price We Pay',
        video: false,
        vote_average: 6,
        vote_count: 77,
      },
    ],
    total_pages: 37320,
    total_results: 746394,
  },
];
